# start or keep
load_model: false
model_name: ddpg_tb3

# Env
stage: 1 # 0: main track, 1: tb3 world

# Reward function
w_angular: 2.0
w_distance: 3.0
alpha_reward: 0.5

# DRL Agent
critic_lr: 0.002
actor_lr: 0.001
gamma: 0.99
tau: 0.005
std_dev: 0.02

batch_size: 128
current_episode: 0
num_episodes: 500
max_steps_per_episode: 250
reward_decay_factor: 0.01
episode_step: 200
save_model_every: 30
aggregate_stats_every: 10
memory_size: 2000000
max_linear_vel: 0.15
max_angular_vel: 0.15

# Logs
base_log_dir: logs
model_save_base_path: keras_models
model_save_path: keras_models/ddpg_tb3.keras
SHOW_QS_VALUES: true

# Miscelanious
log_level: INFO
