# start or keep
load_model: false
model_name: ddpg_tb3

# Env
CARLA_TIMEOUT: 20.0

# DRL Agent
critic_lr: 0.002
actor_lr: 0.001
gamma: 0.99
tau: 0.005
std_dev: 0.2

batch_size: 128
current_episode: 0
num_episodes: 500
episode_step: 500
save_model_every: 30
aggregate_stats_every: 10
memory_size: 1000000
max_angular_vel: 1.5

# Logs
base_log_dir: logs
model_save_path: keras_models/ddpg_tb3.keras
SHOW_QS_VALUES: true

# Miscelanious
log_level: INFO
